### ISSUE TITLE
parson/*.h missing?

### ISSUE THREAD

**Issue by noptrix** [zznop/flyr#20]
Hi, build fails with:

```
--- snip ---
build/release/src/load.c:16:10: fatal error: parson/parson.h: No such file or directory
 #include "parson/parson.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [build/release/src/load.o] Error 1
--- snip ---
```

Cheers,
noptrix

**Comment by zznop** [comment]
Hi noptrix! parson is a git submodule. When you clone flyr use the following command:
```
$ git clone --recursive https://github.com/zznop/flyr.git
```

I should probably add that to the build instructions in the readme. You can also do
```
$ git submodule update --init
```

In your current repository

**Comment by noptrix** [comment]
Damn, i knew it... forgot to try git submodule :) thanks @zznop!

**Comment by zznop** [comment]
Thanks for checking out the project!

**Comment by noptrix** [comment]
> Thanks for checking out the project!

Sure. I like this project. I've even added it to BlackArch Linux: https://github.com/BlackArch/blackarch/blob/feadc0bdd58f330c29d3d67c2e15158ef8c4e0f5/packages/flyr/PKGBUILD
